version: 2.1

executors:
  python-uv:
    docker:
      - image: cimg/python:3.11
    environment:
      UV_CACHE_DIR: /tmp/.uv-cache

workflows:
  main:
    jobs:
      - setup
      - lint:
          requires: [setup]
      - test:
          requires: [setup]
      - type-check:
          requires: [setup]
      - docs:
          requires: [setup]
      - report:
          requires: [lint, test, type-check]

jobs:
  setup:
    executor: python-uv
    steps:
      - checkout
      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            source $BASH_ENV
            uv sync --extra full --extra dev --extra docs --extra test
      - persist_to_workspace:
          root: .
          paths: ["."]

  lint:
    executor: python-uv
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Load UV environment
          command: echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Check code formatting
          command: |
            source $BASH_ENV
            uv run ruff format
            uv run ruff format --check
      - run:
          name: Run linting
          command: |
            source $BASH_ENV
            uv run ruff check --fix

  test:
    executor: python-uv
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Load UV environment
          command: echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Run all test suites
          command: |
            source $BASH_ENV
            uv run python scripts/run_all_tests.py

  type-check:
    executor: python-uv
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Load UV environment
          command: echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Run MyPy type checking
          command: |
            source $BASH_ENV
            uv run mypy src/

  docs:
    executor: python-uv
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Load UV environment
          command: echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Build documentation
          command: |
            source $BASH_ENV
            uv run mkdocs build

  report:
    executor: python-uv
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Load UV environment
          command: echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Generate final coverage report
          command: |
            source $BASH_ENV
            uv run pytest tests/ -m "unit" --cov=src --cov-report=term --cov-fail-under=55
      - run:
          name: Check all quality gates
          command: |
            echo "✅ All quality checks passed!"
            echo "- Code formatting: Checked with Ruff"
            echo "- Linting: Passed with Ruff"
            echo "- Type checking: Passed with MyPy"
            echo "- Unit tests: Passed with coverage ≥55%"
            echo "- Documentation: Built successfully"