[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "message-impl"
version = "1.0.0"
description = "Gmail message implementation"
dependencies = [
    "message",
]
requires-python = ">=3.11"

[tool.uv.sources]
message = { workspace = true }